### ISSUE TITLE
Clarify licence

### ISSUE THREAD

**Issue by rcook** [chpatrick/clang-lens#1]
Patrick,

I'm thinking of contributing to this project at some point in the future, but I'm concerned about the remnants of the Google Individual Contributor License Agreement. I'm guessing that this is a holdover from the [clang-lens](https://github.com/google/clang-lens) project.

Given that this project has the straightforward Apache [licence](https://github.com/chpatrick/clang-pure/blob/master/LICENSE), I'm guessing that this should be a simple as updating [`CONTRIBUTING`](https://github.com/chpatrick/clang-pure/blob/master/CONTRIBUTING) to remove references to the Google Individual Contributor License Agreement.

Thanks, Richard.

**Comment by chpatrick** [comment]
Hi Richard,

I'm glad to hear that you're considering contributing! This project is no longer related to Google, so I have removed the CONTRIBUTING file.
