### ISSUE TITLE
Building clang-pure-0.2.0.2 on Windows

### ISSUE THREAD

**Issue by theoremprover** [chpatrick/clang-lens#11]
Hi there,

I managed to build clang-pure on Windows, but for that I had to change the following:

1.
Remove the "work around a bug in inline-c (?)" in Setup.hs:
#ifdef mingw32_HOST_OS
            ["srcLanguageCClangInternalFFI.c"] -- work around a bug in inline-c (?)
and make it always ["src/Language/C/Clang/Internal/FFI.c"]

2.
In clang-pure.cabal, rename
  extra-libraries:     clang
to
  extra-libraries:     libclang

Then, having --extra-lib-dirs pointing to LLVM\bin, LLVM\lib and
LLVM\lib\clang\3.8.1\lib\windows,
I managed to build clang-pure on windows
(with LLVM 3.8.1 64bit Windows binary installed)

Maybe its worth to include this in the project?

Cheers!
Robert

**Comment by chpatrick** [comment]
I've disabled the workaround on GHC >= 8.0.2 as it is no longer needed.

Specifying the paths was already documented here: https://github.com/chpatrick/clang-pure/blob/master/DEV.md

Renaming `clang` -> `libclang` wasn't necessary for me, did you get Clang from here? http://releases.llvm.org/download.html

**Comment by theoremprover** [comment]
Am 31.10.2017 um 16:09 schrieb Patrick Chilton:
> I've disabled the workaround on GHC >= 8.0.2 as it is no longer needed. >
> Specifying the paths was already documented here: 
> https://github.com/chpatrick/clang-pure/blob/master/DEV.md

Many people (like me) found clang-pure on hackage, and from there
finding DEV.md is not that obvious IMHO.
I'd suggest putting that directly on the hackage page, like
for lens e.g.

> Renaming |clang| -> |libclang| wasn't necessary for me, did you get 
> Clang from here? http://releases.llvm.org/download.html

Yes, from there.

Thanks for your work, by the way. Works like a charm up to now :-)

Cheers!
