### ISSUE TITLE
Outdated description?

### ISSUE THREAD

**Issue by deliciouslytyped** [chpatrick/clang-lens#19]
It looks to me like commits show updates so that the library works with newer llvm/clangs?
The DEV.md should be updated to reflect that it works with newer verisons than llvm 3.8.1?

**Comment by chpatrick** [comment]
Thanks for the issue, I updated it.

**Comment by deliciouslytyped** [comment]
By the way, I saw you have a clang-pure-2 repo, is anything interesting to be expected? :)

**Comment by chpatrick** [comment]
Yes, it's a rewrite mainly with better internals and more complete bindings. It currently only has internal modules and just needs nice public modules that re-export the internal functions. I'm a bit busy to finish it right now, but if you're interested in helping, please let me know. :)

**Comment by deliciouslytyped** [comment]
Sadly, the internals I've looked at seem over my head, I only got bit's and pieces... Amugy, udv kollega ;) elfelejtettem mondani!
